# Header metadata

# Mind no '/' at the and of url
url: papersmile.pl

tmpUrl: http://papersmile.pl

# Company name
companyName: Paper Smile
companyFullName: Paper Smile

title: Paper Smile
description: Paper Smile
keywords: Paper Smile
author: Paper Smile

google_site_verification: x
google_map_apikey: x

analytics: 
    code: x
    domain: papersmile.pl
  
# Social media
social:
    gplus: x
  
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Warsaw

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title/

# Komplety
sets:
  "1":
    "title": "kpl-1-tease.jpg"
  "2":
    "title": "kpl-2-tease.jpg"
  "3":
    "title": "kpl-3-tease.jpg"
  "4":
    "title": "kpl-4-tease.jpg"

produkty:
  karty:
    moje-9-miesiecy:
      nazwa: Karty do zdjęć Moje 9 miesięcy ciąża
      url: /karty-do-zdjec-moje-9-miesiecy-ciaza
      cena: "43.00"
      allegro: http://allegro.pl/karty-do-zdjec-moje-9-miesiecy-ciaza-i6944885530.html
    pierwszy-rok-dziecka:
      nazwa: Karty do zdjęć Pierwszy rok życia dziecka Zwierzęta 39 kart
      url: /karty-do-zdjec-pierwszy-rok-zycia-dziecka-zwierzeta-39-kart
      cena: "42.00"
      allegro: http://allegro.pl/karty-do-zdjec-pierwszy-rok-zycia-dziecka-i6942636972.html
    pierwszy-rok-prezent:
      nazwa: pierwszy-rok-zycia-dziecka-zwierzeta-43-karty
      url: pierwszy-rok-zycia-dziecka-zwierzeta-43-karty
      cena: "45.00"
      allegro: http://allegro.pl/karty-do-zdjec-pierwszy-rok-zycia-prezent-i6992582584.html
    pierwszy-rok-kontrastowe:
      nazwa: pierwszy-rok-zycia kontrastowe-
      nazwa: karty-do-zdjec-pierwszy-rok-zycia-kontrastowe
      cena: "39.00"
      allegro: http://allegro.pl/kontrastowe-karty-do-zdjec-pierwszy-rok-zycia-i7009880037.html
